apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-argo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-argo-api
  template:
    metadata:
      labels:
        app: test-argo-api
    spec:
      containers:
        - name: api
          # built, tagged, and loaded into kind locally.
          # not container registry yet.
          image: test-argo-api:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
