apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-argo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-argo-api
  template:
    metadata:
      labels:
        app: test-argo-api
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: api
          image: ghcr.io/hosackm/test-argo-api:sha-e9f7ece
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
